const data = {
    products: [
      {
        _id: '1',
        name: 'Nikon D850',
        category: 'Photography',
        image: 'https://cdn-4.nikon-cdn.com/e/Q5NM96RZZo-YRYNeYvAi9beHK4x3L-8h09FYyKWnWU6L2l14O7STBw==/Views/1585_D850_left.png',
        price: '850 /day',
        brand: 'Nikon',
        rating: 4.5,
        numReviews: 10,
        description: 'Digital SLR Camera (Black)',
      },
      {
        _id: '2',
        name: 'Canon EOS Rebel T7',
        category: 'Photography',
        image: 'https://in.canon/media/image/2018/03/25/937d6225816f49538c9dac956e8b8a8c_eos-1500d_b1.png',
        price: '250 /day',
        brand: 'Canon',
        rating: 4.0,
        numReviews: 10,
        description: 'Digital SLR Camera (Black)',
      },
      {
        _id: '3',
        name: 'Tripod',
        category: 'Accessories',
        image: 'https://www.bhphotovideo.com/images/images500x500/manfrotto_mvk526twinfaus_526_1_fluid_video_head_1585232814_1507200.jpg',
        price: '850 /day',
        brand: 'Manfratto',
        rating: 4.8,
        numReviews: 17,
        description: 'Tripod Professional',
      },
      {
        _id: '4',
        name: 'Accessories',
        category: 'Kit',
        image: 'https://static.bhphotovideo.com/explora/sites/default/files/02-bolt-vb-11-bare-bulb-flash-and-accessory-kit.png',
        price: '450 /day',
        brand: 'Others',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Canon EOS 5D Mark',
        category: 'Camers',
        image: 'https://in.canon/media/migration/shared/live/products/EN/eos-5d-mk-iv-ef24-105mm-b2.png',
        price: '650 /day',
        brand: 'Canon',
        rating: 4.5,
        numReviews: 10,
        description: 'Professional product',
      },
      {
        _id: '6',
        name: 'Video Recorder',
        category: 'Photography',
        image: "https://image.shopmoment.com/resizer?quality=75&width=1320&fit=cover&gravityX=0.5&gravityY=0.5&height=1320&image=https://image.shopmoment.com/general/Moment-Sony-ILME-FX6Vk-Sony-FX6-Digital-Cinema-Camera-Kit-with-24-105mm-Lens-01.jpg?mtime=20211018202948&focal=none",
        price: '1200 /day',
        brand: 'Sony',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;